//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.33440.
// 
namespace WebServiceLib {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ActivationWebServiceBinding", Namespace="http://www.anshanrayanesh.ir/products/activation/activation.php")]
    public partial class ActivationWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActivateOperationCompleted;
        
        private System.Threading.SendOrPostCallback TrialOperationCompleted;
        
        /// <remarks/>
        public ActivationWebService() {
            this.Url = "http://www.anshanrayanesh.ir/products/activation/activation.php";
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event ActivateCompletedEventHandler ActivateCompleted;
        
        /// <remarks/>
        public event TrialCompletedEventHandler TrialCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.anshanrayanesh.ir/products/activation/activation.php/HelloWorld", RequestNamespace="http://www.anshanrayanesh.ir/products/activation/activation.php", ResponseNamespace="http://www.anshanrayanesh.ir/products/activation/activation.php")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string HelloWorld(string name) {
            object[] results = this.Invoke("HelloWorld", new object[] {
                        name});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHelloWorld(string name, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("HelloWorld", new object[] {
                        name}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndHelloWorld(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync(string name) {
            this.HelloWorldAsync(name, null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(string name, object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[] {
                        name}, this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.anshanrayanesh.ir/products/activation/activation.php/Activate", RequestNamespace="http://www.anshanrayanesh.ir/products/activation/activation.php", ResponseNamespace="http://www.anshanrayanesh.ir/products/activation/activation.php")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public ActivationResponse Activate(ActivationRequest name) {
            object[] results = this.Invoke("Activate", new object[] {
                        name});
            return ((ActivationResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginActivate(ActivationRequest name, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Activate", new object[] {
                        name}, callback, asyncState);
        }
        
        /// <remarks/>
        public ActivationResponse EndActivate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ActivationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ActivateAsync(ActivationRequest name) {
            this.ActivateAsync(name, null);
        }
        
        /// <remarks/>
        public void ActivateAsync(ActivationRequest name, object userState) {
            if ((this.ActivateOperationCompleted == null)) {
                this.ActivateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActivateOperationCompleted);
            }
            this.InvokeAsync("Activate", new object[] {
                        name}, this.ActivateOperationCompleted, userState);
        }
        
        private void OnActivateOperationCompleted(object arg) {
            if ((this.ActivateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActivateCompleted(this, new ActivateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.anshanrayanesh.ir/products/activation/activation.php/Trial", RequestNamespace="http://www.anshanrayanesh.ir/products/activation/activation.php", ResponseNamespace="http://www.anshanrayanesh.ir/products/activation/activation.php")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public ActivationResponse Trial(ActivationRequest name) {
            object[] results = this.Invoke("Trial", new object[] {
                        name});
            return ((ActivationResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTrial(ActivationRequest name, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Trial", new object[] {
                        name}, callback, asyncState);
        }
        
        /// <remarks/>
        public ActivationResponse EndTrial(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ActivationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void TrialAsync(ActivationRequest name) {
            this.TrialAsync(name, null);
        }
        
        /// <remarks/>
        public void TrialAsync(ActivationRequest name, object userState) {
            if ((this.TrialOperationCompleted == null)) {
                this.TrialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTrialOperationCompleted);
            }
            this.InvokeAsync("Trial", new object[] {
                        name}, this.TrialOperationCompleted, userState);
        }
        
        private void OnTrialOperationCompleted(object arg) {
            if ((this.TrialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TrialCompleted(this, new TrialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.anshanrayanesh.ir/products/activation/activation.php")]
    public partial class ActivationRequest {
        
        private string serialNumberField;
        
        private string generationCodeField;
        
        private string activationCodeField;
        
        private string userField;
        
        private string companyField;
        
        private string emailField;
        
        private ActivationType typeField;
        
        private string softwareField;
        
        private string versionField;
        
        /// <remarks/>
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        public string GenerationCode {
            get {
                return this.generationCodeField;
            }
            set {
                this.generationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ActivationCode {
            get {
                return this.activationCodeField;
            }
            set {
                this.activationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public ActivationType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Software {
            get {
                return this.softwareField;
            }
            set {
                this.softwareField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.anshanrayanesh.ir/products/activation/activation.php")]
    public enum ActivationType {
        
        /// <remarks/>
        Full,
        
        /// <remarks/>
        Trial,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.anshanrayanesh.ir/products/activation/activation.php")]
    public partial class ActivationResponse {
        
        private ActivationRequest activationInfoField;
        
        private bool activationResultField;
        
        private string activationMessageField;
        
        /// <remarks/>
        public ActivationRequest ActivationInfo {
            get {
                return this.activationInfoField;
            }
            set {
                this.activationInfoField = value;
            }
        }
        
        /// <remarks/>
        public bool ActivationResult {
            get {
                return this.activationResultField;
            }
            set {
                this.activationResultField = value;
            }
        }
        
        /// <remarks/>
        public string ActivationMessage {
            get {
                return this.activationMessageField;
            }
            set {
                this.activationMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void ActivateCompletedEventHandler(object sender, ActivateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActivateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActivateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActivationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActivationResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void TrialCompletedEventHandler(object sender, TrialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TrialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TrialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActivationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActivationResponse)(this.results[0]));
            }
        }
    }
}
