//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("ClientGlobalSettings", Namespace="", IsNullable=false)]
public partial class GlobalSettings : object, System.ComponentModel.INotifyPropertyChanged {
    
    private GlobalSettingParking parkingSettingField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public GlobalSettingParking ParkingSetting {
        get {
            return this.parkingSettingField;
        }
        set {
            this.parkingSettingField = value;
            this.RaisePropertyChanged("ParkingSetting");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GlobalSettingParking : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string nameField;
    
    private int capacityField;
    
    private GlobalSettingTariff tariffField;
    
    public GlobalSettingParking() {
        this.nameField = "MyParking";
        this.capacityField = 1000;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
            this.RaisePropertyChanged("Name");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Capacity {
        get {
            return this.capacityField;
        }
        set {
            this.capacityField = value;
            this.RaisePropertyChanged("Capacity");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public GlobalSettingTariff Tariff {
        get {
            return this.tariffField;
        }
        set {
            this.tariffField = value;
            this.RaisePropertyChanged("Tariff");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GlobalSettingTariff : object, System.ComponentModel.INotifyPropertyChanged {
    
    private GlobalTariffInfo dayField;
    
    private GlobalTariffInfo nightField;
    
    private int aDayField;
    
    private int freeField;
    
    private int lastField;
    
    public GlobalSettingTariff() {
        this.aDayField = 8000;
        this.freeField = 15;
        this.lastField = 5;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public GlobalTariffInfo Day {
        get {
            return this.dayField;
        }
        set {
            this.dayField = value;
            this.RaisePropertyChanged("Day");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public GlobalTariffInfo Night {
        get {
            return this.nightField;
        }
        set {
            this.nightField = value;
            this.RaisePropertyChanged("Night");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int ADay {
        get {
            return this.aDayField;
        }
        set {
            this.aDayField = value;
            this.RaisePropertyChanged("ADay");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Free {
        get {
            return this.freeField;
        }
        set {
            this.freeField = value;
            this.RaisePropertyChanged("Free");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Last {
        get {
            return this.lastField;
        }
        set {
            this.lastField = value;
            this.RaisePropertyChanged("Last");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GlobalTariffInfo : object, System.ComponentModel.INotifyPropertyChanged {
    
    private int startField;
    
    private int endField;
    
    private int firstField;
    
    private int nextField;
    
    public GlobalTariffInfo() {
        this.startField = 7;
        this.endField = 22;
        this.firstField = 1200;
        this.nextField = 800;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
            this.RaisePropertyChanged("Start");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int End {
        get {
            return this.endField;
        }
        set {
            this.endField = value;
            this.RaisePropertyChanged("End");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int First {
        get {
            return this.firstField;
        }
        set {
            this.firstField = value;
            this.RaisePropertyChanged("First");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Next {
        get {
            return this.nextField;
        }
        set {
            this.nextField = value;
            this.RaisePropertyChanged("Next");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}
