//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("ClientSettings", Namespace="", IsNullable=false)]
public partial class Settings : object, System.ComponentModel.INotifyPropertyChanged {
    
    private SettingParking parkingSettingField;
    
    private SettingANPR aNPRSettingField;
    
    private SettingDatabase databaseSettingField;
    
    private SettingCamera cameraSettingField;
    
    private SettingPrinter printerSettingField;
    
    private SettingCardReader cardReaderSettingField;
    
    private SettingSoftware softwareSettingField;
    
    private SettingBarrier barrierSettingField;
    
    private SettingBoard boardSettingField;
    
    private SettingPayment paymentSettingField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SettingParking ParkingSetting {
        get {
            return this.parkingSettingField;
        }
        set {
            this.parkingSettingField = value;
            this.RaisePropertyChanged("ParkingSetting");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SettingANPR ANPRSetting {
        get {
            return this.aNPRSettingField;
        }
        set {
            this.aNPRSettingField = value;
            this.RaisePropertyChanged("ANPRSetting");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SettingDatabase DatabaseSetting {
        get {
            return this.databaseSettingField;
        }
        set {
            this.databaseSettingField = value;
            this.RaisePropertyChanged("DatabaseSetting");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SettingCamera CameraSetting {
        get {
            return this.cameraSettingField;
        }
        set {
            this.cameraSettingField = value;
            this.RaisePropertyChanged("CameraSetting");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SettingPrinter PrinterSetting {
        get {
            return this.printerSettingField;
        }
        set {
            this.printerSettingField = value;
            this.RaisePropertyChanged("PrinterSetting");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SettingCardReader CardReaderSetting {
        get {
            return this.cardReaderSettingField;
        }
        set {
            this.cardReaderSettingField = value;
            this.RaisePropertyChanged("CardReaderSetting");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SettingSoftware SoftwareSetting {
        get {
            return this.softwareSettingField;
        }
        set {
            this.softwareSettingField = value;
            this.RaisePropertyChanged("SoftwareSetting");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SettingBarrier BarrierSetting {
        get {
            return this.barrierSettingField;
        }
        set {
            this.barrierSettingField = value;
            this.RaisePropertyChanged("BarrierSetting");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SettingBoard BoardSetting {
        get {
            return this.boardSettingField;
        }
        set {
            this.boardSettingField = value;
            this.RaisePropertyChanged("BoardSetting");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SettingPayment PaymentSetting {
        get {
            return this.paymentSettingField;
        }
        set {
            this.paymentSettingField = value;
            this.RaisePropertyChanged("PaymentSetting");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SettingParking : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string nameField;
    
    private int capacityField;
    
    private SettingTariff tariffField;
    
    public SettingParking() {
        this.nameField = "MyParking";
        this.capacityField = 1000;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
            this.RaisePropertyChanged("Name");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Capacity {
        get {
            return this.capacityField;
        }
        set {
            this.capacityField = value;
            this.RaisePropertyChanged("Capacity");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SettingTariff Tariff {
        get {
            return this.tariffField;
        }
        set {
            this.tariffField = value;
            this.RaisePropertyChanged("Tariff");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SettingTariff : object, System.ComponentModel.INotifyPropertyChanged {
    
    private TariffInfo dayField;
    
    private TariffInfo nightField;
    
    private int aDayField;
    
    private int freeField;
    
    private int lastField;
    
    public SettingTariff() {
        this.aDayField = 8000;
        this.freeField = 15;
        this.lastField = 5;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TariffInfo Day {
        get {
            return this.dayField;
        }
        set {
            this.dayField = value;
            this.RaisePropertyChanged("Day");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TariffInfo Night {
        get {
            return this.nightField;
        }
        set {
            this.nightField = value;
            this.RaisePropertyChanged("Night");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int ADay {
        get {
            return this.aDayField;
        }
        set {
            this.aDayField = value;
            this.RaisePropertyChanged("ADay");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Free {
        get {
            return this.freeField;
        }
        set {
            this.freeField = value;
            this.RaisePropertyChanged("Free");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Last {
        get {
            return this.lastField;
        }
        set {
            this.lastField = value;
            this.RaisePropertyChanged("Last");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class TariffInfo : object, System.ComponentModel.INotifyPropertyChanged {
    
    private int startField;
    
    private int endField;
    
    private int firstField;
    
    private int nextField;
    
    public TariffInfo() {
        this.startField = 7;
        this.endField = 21;
        this.firstField = 1200;
        this.nextField = 800;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
            this.RaisePropertyChanged("Start");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int End {
        get {
            return this.endField;
        }
        set {
            this.endField = value;
            this.RaisePropertyChanged("End");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int First {
        get {
            return this.firstField;
        }
        set {
            this.firstField = value;
            this.RaisePropertyChanged("First");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Next {
        get {
            return this.nextField;
        }
        set {
            this.nextField = value;
            this.RaisePropertyChanged("Next");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class PaymentInfo : object, System.ComponentModel.INotifyPropertyChanged {
    
    private bool allowField;
    
    private ComPortInfo portField;
    
    private bool autoSendField;
    
    public PaymentInfo() {
        this.allowField = false;
        this.autoSendField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool Allow {
        get {
            return this.allowField;
        }
        set {
            this.allowField = value;
            this.RaisePropertyChanged("Allow");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ComPortInfo Port {
        get {
            return this.portField;
        }
        set {
            this.portField = value;
            this.RaisePropertyChanged("Port");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool AutoSend {
        get {
            return this.autoSendField;
        }
        set {
            this.autoSendField = value;
            this.RaisePropertyChanged("AutoSend");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ComPortInfo : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string nameField;
    
    private int baudRateField;
    
    public ComPortInfo() {
        this.nameField = "COM1";
        this.baudRateField = 9600;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
            this.RaisePropertyChanged("Name");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int BaudRate {
        get {
            return this.baudRateField;
        }
        set {
            this.baudRateField = value;
            this.RaisePropertyChanged("BaudRate");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SettingPayment : object, System.ComponentModel.INotifyPropertyChanged {
    
    private PaymentInfo cityPayField;
    
    private PaymentInfo pOSField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public PaymentInfo CityPay {
        get {
            return this.cityPayField;
        }
        set {
            this.cityPayField = value;
            this.RaisePropertyChanged("CityPay");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public PaymentInfo POS {
        get {
            return this.pOSField;
        }
        set {
            this.pOSField = value;
            this.RaisePropertyChanged("POS");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SettingCapacity : object, System.ComponentModel.INotifyPropertyChanged {
    
    private ComPortInfo comPortField;
    
    private string addressField;
    
    private int portField;
    
    private string nameField;
    
    private PermissionAllow allowField;
    
    private SettingCapacitySendType sendTypeField;
    
    public SettingCapacity() {
        this.addressField = "127.0.0.1";
        this.portField = 50005;
        this.nameField = "";
        this.allowField = PermissionAllow.No;
        this.sendTypeField = SettingCapacitySendType.Tcp;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ComPortInfo ComPort {
        get {
            return this.comPortField;
        }
        set {
            this.comPortField = value;
            this.RaisePropertyChanged("ComPort");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
            this.RaisePropertyChanged("Address");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Port {
        get {
            return this.portField;
        }
        set {
            this.portField = value;
            this.RaisePropertyChanged("Port");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
            this.RaisePropertyChanged("Name");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(PermissionAllow.No)]
    public PermissionAllow Allow {
        get {
            return this.allowField;
        }
        set {
            this.allowField = value;
            this.RaisePropertyChanged("Allow");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(SettingCapacitySendType.Tcp)]
    public SettingCapacitySendType SendType {
        get {
            return this.sendTypeField;
        }
        set {
            this.sendTypeField = value;
            this.RaisePropertyChanged("SendType");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum PermissionAllow {
    
    /// <remarks/>
    Yes,
    
    /// <remarks/>
    No,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum SettingCapacitySendType {
    
    /// <remarks/>
    Board,
    
    /// <remarks/>
    Tcp,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class BoardInfo : object, System.ComponentModel.INotifyPropertyChanged {
    
    private ComPortInfo portField;
    
    private PermissionAllow allowField;
    
    public BoardInfo() {
        this.allowField = PermissionAllow.No;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ComPortInfo Port {
        get {
            return this.portField;
        }
        set {
            this.portField = value;
            this.RaisePropertyChanged("Port");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(PermissionAllow.No)]
    public PermissionAllow Allow {
        get {
            return this.allowField;
        }
        set {
            this.allowField = value;
            this.RaisePropertyChanged("Allow");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SettingBoard : object, System.ComponentModel.INotifyPropertyChanged {
    
    private BoardInfo priceField;
    
    private SettingCapacity capacityField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BoardInfo Price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
            this.RaisePropertyChanged("Price");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SettingCapacity Capacity {
        get {
            return this.capacityField;
        }
        set {
            this.capacityField = value;
            this.RaisePropertyChanged("Capacity");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class BarrierTypeInfo : object, System.ComponentModel.INotifyPropertyChanged {
    
    private int actTimeField;
    
    private SettingANPRStartType startTypeField;
    
    public BarrierTypeInfo() {
        this.actTimeField = 20;
        this.startTypeField = SettingANPRStartType.Auto;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int ActTime {
        get {
            return this.actTimeField;
        }
        set {
            this.actTimeField = value;
            this.RaisePropertyChanged("ActTime");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(SettingANPRStartType.Auto)]
    public SettingANPRStartType StartType {
        get {
            return this.startTypeField;
        }
        set {
            this.startTypeField = value;
            this.RaisePropertyChanged("StartType");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum SettingANPRStartType {
    
    /// <remarks/>
    Auto,
    
    /// <remarks/>
    Manual,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class BarrierInfo : object, System.ComponentModel.INotifyPropertyChanged {
    
    private ComPortInfo portField;
    
    private BarrierTypeInfo openField;
    
    private BarrierTypeInfo closeField;
    
    private PermissionAllow allowField;
    
    public BarrierInfo() {
        this.allowField = PermissionAllow.No;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ComPortInfo Port {
        get {
            return this.portField;
        }
        set {
            this.portField = value;
            this.RaisePropertyChanged("Port");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BarrierTypeInfo Open {
        get {
            return this.openField;
        }
        set {
            this.openField = value;
            this.RaisePropertyChanged("Open");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BarrierTypeInfo Close {
        get {
            return this.closeField;
        }
        set {
            this.closeField = value;
            this.RaisePropertyChanged("Close");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(PermissionAllow.No)]
    public PermissionAllow Allow {
        get {
            return this.allowField;
        }
        set {
            this.allowField = value;
            this.RaisePropertyChanged("Allow");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SettingBarrier : object, System.ComponentModel.INotifyPropertyChanged {
    
    private BarrierInfo enterField;
    
    private BarrierInfo exitField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BarrierInfo Enter {
        get {
            return this.enterField;
        }
        set {
            this.enterField = value;
            this.RaisePropertyChanged("Enter");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BarrierInfo Exit {
        get {
            return this.exitField;
        }
        set {
            this.exitField = value;
            this.RaisePropertyChanged("Exit");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ServerInfo : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string addressField;
    
    private int portField;
    
    private PermissionAllow allowField;
    
    public ServerInfo() {
        this.addressField = "127.0.0.1";
        this.portField = 50006;
        this.allowField = PermissionAllow.No;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
            this.RaisePropertyChanged("Address");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Port {
        get {
            return this.portField;
        }
        set {
            this.portField = value;
            this.RaisePropertyChanged("Port");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(PermissionAllow.No)]
    public PermissionAllow Allow {
        get {
            return this.allowField;
        }
        set {
            this.allowField = value;
            this.RaisePropertyChanged("Allow");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SettingSoftware : object, System.ComponentModel.INotifyPropertyChanged {
    
    private ServerInfo serverField;
    
    private Permission enterField;
    
    private Permission exitField;
    
    private int portField;
    
    private string skinField;
    
    public SettingSoftware() {
        this.portField = 50005;
        this.skinField = "default";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ServerInfo Server {
        get {
            return this.serverField;
        }
        set {
            this.serverField = value;
            this.RaisePropertyChanged("Server");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Permission Enter {
        get {
            return this.enterField;
        }
        set {
            this.enterField = value;
            this.RaisePropertyChanged("Enter");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Permission Exit {
        get {
            return this.exitField;
        }
        set {
            this.exitField = value;
            this.RaisePropertyChanged("Exit");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Port {
        get {
            return this.portField;
        }
        set {
            this.portField = value;
            this.RaisePropertyChanged("Port");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Skin {
        get {
            return this.skinField;
        }
        set {
            this.skinField = value;
            this.RaisePropertyChanged("Skin");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Permission : object, System.ComponentModel.INotifyPropertyChanged {
    
    private PermissionAllow allowField;
    
    public Permission() {
        this.allowField = PermissionAllow.No;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(PermissionAllow.No)]
    public PermissionAllow Allow {
        get {
            return this.allowField;
        }
        set {
            this.allowField = value;
            this.RaisePropertyChanged("Allow");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SettingCardReader : object, System.ComponentModel.INotifyPropertyChanged {
    
    private ComPortInfo enterField;
    
    private ComPortInfo exitField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ComPortInfo Enter {
        get {
            return this.enterField;
        }
        set {
            this.enterField = value;
            this.RaisePropertyChanged("Enter");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ComPortInfo Exit {
        get {
            return this.exitField;
        }
        set {
            this.exitField = value;
            this.RaisePropertyChanged("Exit");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SettingPrinter : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string lyricField;
    
    private string nameField;
    
    private PermissionAllow allowField;
    
    public SettingPrinter() {
        this.lyricField = "Sample Lyric";
        this.nameField = "none";
        this.allowField = PermissionAllow.No;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Lyric {
        get {
            return this.lyricField;
        }
        set {
            this.lyricField = value;
            this.RaisePropertyChanged("Lyric");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
            this.RaisePropertyChanged("Name");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(PermissionAllow.No)]
    public PermissionAllow Allow {
        get {
            return this.allowField;
        }
        set {
            this.allowField = value;
            this.RaisePropertyChanged("Allow");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CameraInfo : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string uRLField;
    
    private bool saveField;
    
    private PermissionAllow allowField;
    
    public CameraInfo() {
        this.uRLField = "http://admin:admin@192.168.1.160:80/snap.jpg?usr=admin&pwd=admin";
        this.saveField = true;
        this.allowField = PermissionAllow.No;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string URL {
        get {
            return this.uRLField;
        }
        set {
            this.uRLField = value;
            this.RaisePropertyChanged("URL");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool Save {
        get {
            return this.saveField;
        }
        set {
            this.saveField = value;
            this.RaisePropertyChanged("Save");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(PermissionAllow.No)]
    public PermissionAllow Allow {
        get {
            return this.allowField;
        }
        set {
            this.allowField = value;
            this.RaisePropertyChanged("Allow");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SettingCamera : object, System.ComponentModel.INotifyPropertyChanged {
    
    private CameraInfo enterField;
    
    private CameraInfo exitField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CameraInfo Enter {
        get {
            return this.enterField;
        }
        set {
            this.enterField = value;
            this.RaisePropertyChanged("Enter");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CameraInfo Exit {
        get {
            return this.exitField;
        }
        set {
            this.exitField = value;
            this.RaisePropertyChanged("Exit");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SettingDatabase : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string serverField;
    
    private string usernameField;
    
    private string passwordField;
    
    private int portField;
    
    private string databaseField;
    
    public SettingDatabase() {
        this.serverField = "localhost";
        this.usernameField = "root";
        this.passwordField = "123456";
        this.portField = 3306;
        this.databaseField = "parspark";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Server {
        get {
            return this.serverField;
        }
        set {
            this.serverField = value;
            this.RaisePropertyChanged("Server");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Username {
        get {
            return this.usernameField;
        }
        set {
            this.usernameField = value;
            this.RaisePropertyChanged("Username");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
            this.RaisePropertyChanged("Password");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Port {
        get {
            return this.portField;
        }
        set {
            this.portField = value;
            this.RaisePropertyChanged("Port");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Database {
        get {
            return this.databaseField;
        }
        set {
            this.databaseField = value;
            this.RaisePropertyChanged("Database");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SettingANPR : object, System.ComponentModel.INotifyPropertyChanged {
    
    private Permission enterField;
    
    private Permission exitField;
    
    private PermissionAllow allowField;
    
    private SettingANPRStartType startTypeField;
    
    public SettingANPR() {
        this.allowField = PermissionAllow.No;
        this.startTypeField = SettingANPRStartType.Auto;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Permission Enter {
        get {
            return this.enterField;
        }
        set {
            this.enterField = value;
            this.RaisePropertyChanged("Enter");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Permission Exit {
        get {
            return this.exitField;
        }
        set {
            this.exitField = value;
            this.RaisePropertyChanged("Exit");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(PermissionAllow.No)]
    public PermissionAllow Allow {
        get {
            return this.allowField;
        }
        set {
            this.allowField = value;
            this.RaisePropertyChanged("Allow");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(SettingANPRStartType.Auto)]
    public SettingANPRStartType StartType {
        get {
            return this.startTypeField;
        }
        set {
            this.startTypeField = value;
            this.RaisePropertyChanged("StartType");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}
