//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class cards
    {
        public long id { get; set; }
        public string code { get; set; }
        public string key { get; set; }
        public System.DateTime submit { get; set; }
    }
}
