//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class lostcard
    {
        public long id { get; set; }
        public string cardid { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public long driverID { get; set; }
        public string dlicense { get; set; }
        public string license { get; set; }
        public string phone { get; set; }
        public string type { get; set; }
        public int fine { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> submitdate { get; set; }
    }
}
