//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class parsparkoEntities : DbContext
    {
		public parsparkoEntities(string ConnectionString)
			: base("name=parsparkoEntities")
		{
			this.Database.Connection.ConnectionString = ConnectionString;
			this.Database.CommandTimeout = 5;
		}

		protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<blacklist> blacklist { get; set; }
        public virtual DbSet<car> car { get; set; }
        public virtual DbSet<cards> cards { get; set; }
        public virtual DbSet<driver> driver { get; set; }
        public virtual DbSet<enterlogs> enterlogs { get; set; }
        public virtual DbSet<logs> logs { get; set; }
        public virtual DbSet<lostcard> lostcard { get; set; }
        public virtual DbSet<settings> settings { get; set; }
        public virtual DbSet<subscription> subscription { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
