//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public long id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public byte[] picture { get; set; }
        public string type { get; set; }
        public System.DateTime register { get; set; }
    }
}
