//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParsPark._1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class exit
    {
        public decimal id { get; set; }
        public string code { get; set; }
        public string license { get; set; }
        public System.DateTime enter { get; set; }
        public Nullable<System.DateTime> exit1 { get; set; }
        public Nullable<decimal> cost { get; set; }
        public byte[] enpicture { get; set; }
        public byte[] expicture { get; set; }
        public string type { get; set; }
        public Nullable<decimal> enuser { get; set; }
        public Nullable<decimal> exuser { get; set; }
    }
}
