//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParsPark._1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscription
    {
        public decimal id { get; set; }
        public string code { get; set; }
        public decimal drivercarid { get; set; }
        public decimal cost { get; set; }
        public System.DateTime startdate { get; set; }
        public System.DateTime enddate { get; set; }
        public System.DateTime register { get; set; }
    
        public virtual car car { get; set; }
    }
}
